package dev.meinicke.plugin.annotation;

import java.lang.annotation.*;

/**
 * Container annotation for repeating {@link Attribute} annotations.
 * <p>
 * This annotation enables multiple {@code @Attribute} declarations to be applied to the same element,
 * in accordance with the {@link Repeatable} contract.
 * <p>
 * This container is automatically generated by the compiler when multiple {@link Attribute} annotations
 * are used on a single element, and is not typically used directly.
 * </p>
 *
 * @see Attribute
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.TYPE)
public @interface Attributes {

    /**
     * The array of {@link Attribute} annotations.
     *
     * @return the repeated attribute declarations
     */
    Attribute[] value();
}
